### PR TITLE
GetMessages and GetMessageById methods

### PR DESCRIPTION
**Pull request by tarasverq**
Hi Ilya!

Some new useful methods for library

### CODE REVIEW

**Comment by ilyalatt** [comment]
I've simplified the code. I am not sure that `.OrderBy(x => x.Id)` is needed. Are you sure that fetched messages are not sorted by id already?

**Comment by tarasverq** [comment]
I'm not sure about sorting, this was just to be sure.

By the way this approach will not work:
```
 var groupId = messages.Find(x => x.Id == messageId).Bind(x => x.GroupedId);
 return messages.Filter(x => x.GroupedId == groupId);
```

In case of single message `groupId ` variable will be `Option.None`, so you will return all single messages near `messageId`.
We should check `groupId` for `None` option.

**Comment by ilyalatt** [comment]
Yeah, but it is fixed already

**Comment by ilyalatt** [comment]
Can you verify that id's are ordered and the method works as expected?

**Comment by tarasverq** [comment]
checked: ids is in ascending order

**Comment by ilyalatt** [comment]
good

**Pull request merged**
